### ISSUE TITLE
ListBucket Permission

### ISSUE THREAD

**Issue by leezu** [aws/sagemaker-python-sdk#1283]
**Describe the bug**
With `model = MXNetModel('s3://lausen-public/bert_sst.tar.gz',`, your package attempts to list the lausen-public bucket and fails due to lack of permission. Note that while I don't grant you permission to list my bucket, `'s3://lausen-public/bert_sst.tar.gz` is public.

**Expected behavior**
No need to list bucket. Just take the public file.

**Screenshots or logs**
https://cbx2jz1ir3.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=fa40d2ee-eb3d-48c4-b361-075697d5d814%2Fbuild.log

**System information**
CI run of https://github.com/aws/sagemaker-mxnet-serving-container/pull/94

**Comment by laurenyu** [comment]
thanks for bringing this to our attention!

the reason we use a `ListObjects` call is to [determine whether or not the S3 path is a directory](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L347-L353). Since both folders and single objects are allowed, the code has to be able to handle both. Unfortunately, S3 doesn't provide a clean way to [check if an object is a folder](https://stackoverflow.com/questions/22312833/how-can-you-tell-if-an-object-is-a-folder-on-aws-s3), so that's where the `ListObjects` call comes into play.

I do think we can flip the logic around to make this work, and I'll try to post an update here when I can

**Comment by laurenyu** [comment]
https://github.com/aws/sagemaker-python-sdk/pull/1295

**Comment by laurenyu** [comment]
fix was released in [v1.50.13](https://github.com/aws/sagemaker-python-sdk/releases/tag/v1.50.13)
