### ISSUE TITLE
Wrong Enum Values for Transformer `strategy`

### ISSUE THREAD

**Issue by jaredleekatzman** [aws/sagemaker-python-sdk#1333]
**What did you find confusing? Please describe.**
When trying to build a transformer from a TensorFlowModel, e.g.

```
transformer = model.transformer(
    instance_count=1, instance_type='ml.m5.large', assemble_with='Line',
    accept='application/json', output_path=output_uri, strategy='SingleRecord'
)
```

The doc string gave wrong information for the parameter `strategy`. The Doc says the values  must be of either `[MULTI_RECORD, SINGLE_RECORD]`. I tried them but then the API throws an error. 

When you look  at the Transformer API [doc string](https://github.com/aws/sagemaker-python-sdk/blob/fda585bc609e0341d02232f8228787866a5d4504/src/sagemaker/transformer.py#L54-L56) the value of  the strings mus be of  either `[MultiRecord, SingleRecord]`, and there doesn't seem to be a value translation.  

**Describe how documentation can be improved**
The right values of the `strategy` parameter should be mentioned correctly across  the sagemaker-python-sdk documentation. There seems to be  7-8 occurrses across the GitHub Repo [link](https://github.com/aws/sagemaker-python-sdk/search?q=SINGLE_RECORD&unscoped_q=SINGLE_RECORD):

- entities.py
- pipeline.py
- algorithm.py
- model.py
- tensorflow/estimator.py
- airflow.py
- estimator.py
- session.py

**Comment by knakad** [comment]
Oh no! Thanks for bringing this to our attention!

It looks like there were already unit tests and integ tests validation the functionality using the properly cased version of the strings (SingleRecord/MultiRecord). However, as you pointed out, the docstrings were wrong (likely because the backend uses the screaming snake case version, which is also reflected in our local mode code).

I submitted and merged PR to fix this: https://github.com/aws/sagemaker-python-sdk/pull/1340
Note that the readthedocs pages will only be updated on the next release, which is the morning after the commit is merged (on a non_Friday weekday). In this case, tomorrow morning, barring unforeseen circumstances.

Thanks again for letting us know!
