### ISSUE TITLE
SDK 2.0: image_uris.retrieve() fails for XGBoost 1.0-1

### ISSUE THREAD

**Issue by juliensimon** [aws/sagemaker-python-sdk#1748]
Using the latest build of SDK v2:

```
region = boto3.Session().region_name    
container = image_uris.retrieve('xgboost', region, version='1.0-1')
```
**ValueError: Empty SageMaker instance type. For options, see: https://aws.amazon.com/sagemaker/pricing/instance-types**

Replacing '1.0-1' with 'latest' works.

**Comment by laurenyu** [comment]
this is because currently `image_uris.retrieve()` expects an instance type to determine gpu vs cpu for frameworks - however it would be redundant for XGBoost and scikit-learn, which both support only CPU. I'll update `image_uris.retrieve()` so that the instance type isn't required if there's only one processor type available.

**Comment by juliensimon** [comment]
Makes sense. Thanks!

**Comment by laurenyu** [comment]
merged #1788 to address this issue

**Comment by itsencrypted** [comment]
[https://youtu.be/DHQYwhFiEDI] - I tried using 'latest' instead of version '1.0-1' and in both cases I'm getting the same error message: 
FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/image_uri_config/us-east-1.json'

My bucket and jupyter notebook are both on us-east-1.

**Comment by laurenyu** [comment]
@itsencrypted you need to swap the order of your first two arguments for `retrieve()`:

```python
container = sagemaker.image_uris.retrieve('xgboost', region, 'latest')
```

docs: https://sagemaker.readthedocs.io/en/stable/api/utility/image_uris.html#sagemaker.image_uris.retrieve

if you need more assistance, please open a new issue (since this one is closed).
