### ISSUE TITLE
Local Mode does not work on Sagemaker Studio

### ISSUE THREAD

**Issue by bloodywolf3** [aws/sagemaker-python-sdk#1842]
**Describe the bug**
I am trying to do training in a local container by running the example python notebook: mxnet_gluon_mnist/mxnet_mnist_with_gluon_local_mode.ipynb

**To reproduce**
A clear, step-by-step set of instructions to reproduce the bug.
In the sagemaker studio window
1) Select a) MXNET GPU optimized kernel and b) ml.g4dn.xlarge instance
2) Running the script: !/bin/bash ./setup.sh
The output is ./setup.sh: line 3: sudo: command not found
The user does not have root access. Everything required to run the notebook is already installed and setup. We are good to go!
3) Run m.fit(inputs)
The output is ImportError: 'docker-compose' is not installed. Local Mode features will not work without docker-compose. For more information on how to install 'docker-compose', please, see https://docs.docker.com/compose/install/

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: MXNET GPU optimized kernel 
- **Framework version**: 
- **Python version**: 3 
- **CPU or GPU**:  ml.g4dn.xlarge 
- **Custom Docker image (Y/N)**: N

**Additional context**

**Comment by metrizable** [comment]
Hello @bloodywolf3 
    
Thank you for using Amazon SageMaker. I understand that you want to use local mode with SageMaker Studio but the `setup.sh` script [here](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/mxnet_gluon_mnist/setup.sh) does not work/install `docker-compose` and make other configurations.

There are several limitations to running the local mode setup.sh script in Studio. At the very least, a refactor of the script would be required to work with a Debian-based Linux system. You can check the OS release of your running environment, say, in a Studio cell:
```
[1]:  !lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.6 LTS
    Release:	16.04
    Codename:	xenial
```
There are other hurdles to tackle on the way re: nvidia, docker network setup, and ip tables, among others.

This issue is probably best tracked in the [example notebooks repo](https://github.com/awslabs/amazon-sagemaker-examples). Since that repo is owned by a related by different github org (awslabs versus aws), I [cannot](https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository) directly transfer the issue there.

We are always re-evaluating our backlog of features based on customer requests, so we appreciate the feedback on this feature.
    
Let us know if there is anything else we can be an assistance of.
    
Best regards

**Comment by bloodywolf3** [comment]
Thanks for the prompt reply. I have posted this issue on https://github.com/awslabs/amazon-sagemaker-examples

**Comment by samdwar1976** [comment]
I have written an article describing a solution that makes it possible to use 'Local Mode' in SageMaker Studio. I am add the url below for

**Comment by samdwar1976** [comment]
I have written an [article](https://medium.com/@sam.edwards1976/local-mode-training-and-inference-in-sagemaker-studio-3062d10ae603) describing a solution that makes it possible to use 'Local Mode' in SageMaker Studio. Apologies for opening a closed issue, but adding this for completeness.
