### ISSUE TITLE
Cannot see Clarify results in ModeMetric? ModelMetric has not been Integrated with or the integration is not functioning as expected for Clarify to include its results from a Clarify job into the Model Metric class .  Reference ModelMetric class : https://github.com/aws/sagemaker-python-sdk/blob/b97e355d6a9a627d26a81b773b414d5ff3b405fa/src/sagemaker/model_metrics.py 

### ISSUE THREAD

**Issue by aarsanjani** [aws/sagemaker-python-sdk#2088]
**Describe the bug**

**To reproduce**
A clear, step-by-step set of instructions to reproduce the bug.

**Expected behavior**

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**:
- **Python version**:
- **CPU or GPU**:
- **Custom Docker image (Y/N)**:

**Additional context**

**Comment by xgchena** [comment]
Thanks for reporting the issue. Would you update the issue description with more details, like steps to reproduce it, screenshots or logs that show the problem, and the expected behavior?

To my understanding [the ModelMetrics class](https://github.com/aws/sagemaker-python-sdk/blob/b97e355d6a9a627d26a81b773b414d5ff3b405fa/src/sagemaker/model_metrics.py) is for [SageMaker Model Registry](https://docs.aws.amazon.com/sagemaker/latest/dg/model-registry.html), and the metrics of a model are available only when the model is used by [SageMaker Model Monitor](https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor.html). Among the four monitoring types, there are two Clarify Model Monitors: [Model Bias Monitor](https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-model-monitor-bias-drift.html) and [Model Explainability Monitor](https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-model-monitor-bias-drift.html). Besides storing analysis results to S3 bucket, they also publish CloudWatch metrics for monitoring executions.

Currently a "vanilla" Clarify processing job only stores analysis results to S3 bucket. Here is a sample notebook for [using SageMaker Clarify processing job to detect bias and explain model predictions with feature attributions](https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker_processing/fairness_and_explainability/fairness_and_explainability.ipynb).

**Comment by pinaraws** [comment]
We have published a blog and associated code examples to show how to use SageMaker Clarify in SageMaker Pipelines.
https://aws.amazon.com/blogs/machine-learning/architect-and-build-the-full-machine-learning-lifecycle-with-amazon-sagemaker/
https://github.com/aws/amazon-sagemaker-examples/tree/master/end_to_end
https://github.com/aws/amazon-sagemaker-examples/blob/master/end_to_end/5-pipeline-e2e.ipynb

Clarify metrics are registered as ModelMetrics after the processing job is run.
https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_ModelMetrics.html
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/model_metrics.py#L66-L69

https://github.com/aws/amazon-sagemaker-examples/blob/master/end_to_end/2-lineage-train-assess-bias-tune-registry-e2e.ipynb

```
model_metrics = {
    'ModelQuality': {
        'Statistics': {
            'ContentType': 'application/json',
            'S3Uri': f's3://{bucket}/{prefix}/{metrics_s3_key}'
        }
    },
    'Bias': {
        'Report': {
            'ContentType': 'application/json',
            'S3Uri': f'{bias_report_1_output_path}/analysis.json'
        }
    }
}

So this is working as expected. Please close the issue or indicate any other gaps or feature requests that remain.
```
