### ISSUE TITLE
Support for slim based models?

### ISSUE THREAD

**Issue by niyazpk** [aws/sagemaker-python-sdk#22]
Is there any way to use sagemaker for training/testing the (imagenet pretrained) models that come with [TF models](https://github.com/tensorflow/models/tree/master/research/object_detection) (these are based on TF slim)? Is there any documentation that you can point me towards for this?

Thanks!

**Comment by iquintero** [comment]
Hi @niyazpk 

Thanks for your interest in SageMaker!

Yes, you can use an existing model using the python sdk. You can do it through your [model_fn](https://github.com/aws/sagemaker-python-sdk#creating-a-model_fn)

We have an example for that available [here](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_resnet_cifar10_with_tensorboard/source_dir/resnet_cifar_10.py#L39) using the model fn to create a resnet network.

In your case the parameters are already pre trained.  Also TF slim is compatible with regular TF so that should not be any issue.

**Comment by mvsusp** [comment]
Hi @niyazpk,

I am going to close this ticket. Feel free to open it again if you need additional assistance.

Thanks for using SageMaker.
