### ISSUE TITLE
IngestionManagerPandas doesn't propagate Boto3 Session profile_name to Workers

### ISSUE THREAD

**Issue by apriceaws** [aws/sagemaker-python-sdk#2298]
**Describe the bug**
When ingesting a DataFrame to a FeatureGroup, there is no way to set the profile_name in the Boto3 Session used by IngestionManagerPandas workers/threads. This prevents utilizing anything but default credentials when ingesting to a FeatureGroup using this class.

**To reproduce**
1. Ensure "default" creds profile does not have access to write to FeatureGroup
2. Ensure "<profile_name>" creds profile does have access to write to FeatureGroup
3. Set a profile_name on boto3 using boto3.setup_default_session(profile_name=<profile_name>)
4. Attempt to ingest a dataframe to a FeatureGroup using <featuregroup>.ingest()
5. Ingest will fail because "default" creds do not have access, and "<profile_name>" creds will not be used in the workers

**Expected behavior**
Worker Boto3 sessions should be initialized with a profile name which matches boto3.DEFAULT_SESSION.profile_name.

**System information**
A description of your system. Please provide:
- SageMaker 2.38.0

**Additional context**
Use of default credentials is not an option in this context.

**Comment by apriceaws** [comment]
Confirmed that this worked fine in SageMaker 2.37

**Comment by ahsan-z-khan** [comment]
@alex-tang , can you take a look at this?

**Comment by gustavovaliati** [comment]
Any news on that? We still have got the same issue at v2.51.

**Comment by kusumbhatt** [comment]
@apriceaws Apologies for getting back to this so late.

Earlier the profile name was not trickled down to the worker sessions in the ingest(..) method and hence the workers were making use of default credentials.

[This](https://github.com/aws/sagemaker-python-sdk/commit/e4b851da7dcd85baa818e985d109d1eac6f821ab) now supports providing "profile_name" as an argument in ingest(..) method and the worker sessions are initialized with the profile parameter. So, in order to use the profile_name different than default, it should be passed to profile_name argument in the ingest(..) method. In case, the profile_name argument is not specified, the ingest(..) method uses the default credentials.

Can you please confirm if this helps you?

**Comment by zhaoqizqwang** [comment]
Closing this ticket since the profile_name is supported as an argument in newer sagemaker
