### ISSUE TITLE
Low Level Python Boto End to End

### ISSUE THREAD

**Issue by BFMarks** [aws/sagemaker-python-sdk#23]
This is definitely an "enhancement" note but why don't your docs have an end to end Python Low Level example?  I have to jump between boto and the notebook code when I really just want the low level code.   I think people would definitely appreciate an example script with TensorFlow or something with maybe the best way to get the docker image working with it.  Just a thought - thanks!

**Comment by iquintero** [comment]
Hi @BFMarks  Thanks for your suggestion. We do want to have an end to end low level example. We will update this issue when we have an ETA on it :)

**Comment by BFMarks** [comment]
Thank you so much!  Any other resources you have for getting the data inputted to the docker image model would also be great!

**Comment by mohanasudhan** [comment]
@BFMarks  Is there any specific example that you are looking for? As this issue was created 6 years ago, I am not sure if this issue is still valid now. 

We have boto3 samples in the SageMaker examples (as one in the below).
https://github.com/aws/amazon-sagemaker-examples/blob/main/boto3/built-in-frameworks/scikit-learn/boto3_scikit_retrain_model_and_deploy_to_existing_endpoint/boto3_scikit_retrain_model_and_deploy_to_existing_endpoint.ipynb

Happy to help if it is still an issue.

**Comment by mohanasudhan** [comment]
We are closing this issue as we currently lack sufficient information to proceed. Please feel free to reopen the issue if you can provide more details.
