### ISSUE TITLE
Allow Sagemaker Studio pipeline parameter optional

### ISSUE THREAD

**Issue by sandipto-sanyal** [aws/sagemaker-python-sdk#2315]
**Describe the feature you'd like**
Currently all Sagemaker Studio pipeline parameters are essential. It will be great if they can be made optional using some parameters to choose whether to make it optional or necessary.

**How would this feature be used? Please describe.**
Since we have to demo the CICD pipeline for different use-cases to senior leaderships of our company hard-coded stuffs on optional parameters creates a negative notion during demos. When parameters are optional and we choose not to enter any value there, it should pass None in the backend Parameter objects.

**Describe alternatives you've considered**
As of now we are hard-coding with junk strings/numbers (like JUNK_STRING/-999999) in order to handle the scenarios.

**Additional context**

**Comment by EthanShouhanCheng** [comment]
@sandipto-sanyal thanks for your inputs and I'm currently looking into this issue. To better help me understanding the question, would you mind clarify a few things? 

What parameters are you trying to omit when you are doing the demo? 
Is this `[parameter](https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html?highlight=pipeline#sagemaker.workflow.pipeline.Pipeline.parameters)` you want to make optional?
Or other pipeline parameters passed to pipeline? 

For  `[parameter](https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html?highlight=pipeline#sagemaker.workflow.pipeline.Pipeline.parameters)`, it is needed because you must specify parameters and their default values(if you want to give any) so that the pipeline definition can be validated; passing None will result an error. However, if you have specified default values when you creating the pipeline, you can omit parameter when you start the pipeline; it will use the default values for executions. 

For `[steps](https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html?highlight=pipeline#sagemaker.workflow.pipeline.Pipeline.steps)`, a minimum of one step is required.

**Comment by jerrypeng7773** [comment]
no response, feel free to re-open @sandipto-sanyal
