### ISSUE TITLE
Parameter `entry-point` for `PyTorchModel` required when using own image

### ISSUE THREAD

**Issue by johann-petrak** [aws/sagemaker-python-sdk#2479]
I am trying to use my own image which I specify with the  `image_uri` parameter to PyTorchModel. This image avoids the unnecessary model-archiver step as it is easier to provide the proper model.mar file directly. The model.mar file also contains its own torch serve handler which avoids the  AWS handler which loads the model at the time of the first request and instead loads it when the handler gets instatiated. 

So, for that image and probably a number of other solutions where an own image is provided, no entry-point file is needed, yet the parameter cannot be left unset. 

This is also annoying as I am providing the tar.gz file that already contains everything needed, but then the SDK untars this, adds the handler as code/handlername.py and tars it again which in this case is completely unnecessary. 

When running this purely locally, the library also incorrrectly then tries to upload the model to S3 which produces a request timeout exception for a large tar.gz file, see https://github.com/aws/sagemaker-python-sdk/issues/2463

**Comment by oborchers** [comment]
@johann-petrak:

Thank you very much for the detailed answer. 

The reason I was asking was mainly due to the fact, that it seems to me this image does not work for larger models at all. If they exceed a certain size, I was never able to get the docker container to run or to produce any logs whatsoever. Presumably, because the capacity of the disk was exceeded, which causes the health-check to fail.

In this case, going for a similar approach might work for me, but the `HuggingFaceModel` does not seem to have that kind of limitation inherent to the system. Perhaps it might be also helpful for you?

Yes, I can see your frustration to the fullest. When I started working with the platform I was amazed how easy it was to get to run some of the examples, but that's where it ends. As soon as you like to customize even a little bit you're in for trouble. Took me about a week to figure out how to run custom docker images. Not to mention the broken `local_mode`, the horrendous error reporting and stuff like that (missing logs, etc.).

**Comment by jeniyat** [comment]
The entry point for the estimator can be any python source code. Below is an example:

```
from sagemaker.huggingface import HuggingFace
import sagemaker

role = sagemaker.get_execution_role()

git_config = {'repo': 'https://github.com/huggingface/transformers.git','branch': 'master'}

hf = HuggingFace(
        py_version="py36",
        instance_count=1,
        instance_type="ml.p3.2xlarge",
        transformers_version='4.6.1',
        pytorch_version='1.7.1',
        enable_sagemaker_metrics=False,
        entry_point='run_glue.py',
        source_dir='./examples/text-classification',
        git_config=git_config,
        role = role
    )

```

You can find more details here: https://sagemaker.readthedocs.io/en/stable/overview.html#use-scripts-stored-in-a-git-repository

**Comment by johann-petrak** [comment]
@jeniyat that was not the point of this issue at all: as I said, the image i use already has the entry point source code so it is utterly useless to require that it gets specified.
