### ISSUE TITLE
How to increase inference timeout

### ISSUE THREAD

**Issue by Harathi123** [aws/sagemaker-python-sdk#2574]
Hi,

Where do we need to specify the environmental Variable GUNICORN_CMD_ARGS='--timeout 1200' to increase inference time? Both for a custom container and sagemaker built-in containers.
Any suggestions will be helpful!
Thanks in advance,
Harathi

**Comment by jkroll-aws** [comment]
Maximum inference timeout is still 60 seconds. Moved to SageMaker Python SDK repository since this is not related to an example.

**Comment by mohanasudhan** [comment]
@shwangdev @pavolzibrita @Harathi123 @pavolzibrita @cipri-tom SageMaker supports multiple timeout parameters to control the model, container loading and invoke call. 

ContainerStartupHealthCheckTimeoutInSeconds - helps with container startup health check
ModelDataDownloadTimeoutInSeconds - helps with model download timeout

(More details can be found in: https://docs.aws.amazon.com/sagemaker/latest/dg/large-model-inference-hosting.html)

And the model servers inside containers provide control on the invoke call. For example, SAGEMAKER_TS_RESPONSE_TIMEOUT and SAGEMAKER_MODEL_SERVER_TIMEOUT can help in controlling the invoke timeout.

Please reopen if you still have issue with timeout.

**Comment by Manishthakur2503** [comment]
Hi ,
I have deployed my Docker image to AWS ECR, created a model, and configured an endpoint with 6GB of RAM for serverless inference in SageMaker. The endpoint works fine with shorter video inputs (e.g., 10 seconds), but when I send a 3-minute long video, I encounter a 500 error.

Initially, I suspected it was a memory issue, but upon checking, the memory utilization is only around 25%. I'm wondering if the error is related to a timeout issue.

Is this likely due to a timeout limit for serverless inference?
If yes, is there a way to increase the timeout limit for serverless inference?
Would increasing the timeout in my Docker container’s server file where I am using gunicorn help resolve this issue?
Any guidance on resolving this would be appreciated!

Thank you.

**Comment by jeromeCondere** [comment]
Hi,
so I have seen that a lot of people wanted to increase the startup timeout for the inference,
Since I couldn't find anything useful on sagemaker documentation I have had a look a  the sagemaker code  (this is in the [https://github.com/aws/sagemaker-pytorch-inference-toolkit/tree/master/src/sagemaker_pytorch_serving_container](https://github.com/aws/sagemaker-pytorch-inference-toolkit/tree/master/src/sagemaker_pytorch_serving_container))

The first thing is that they only added the response timeout in ts_environment.py file
```   def __init__(self):
        self._batch_size = int(os.environ.get(ts_parameters.MODEL_SERVER_BATCH_SIZE, DEFAULT_TS_BATCH_SIZE))
        self._max_batch_delay = int(os.environ.get(ts_parameters.MODEL_SERVER_MAX_BATCH_DELAY,
                                    DEFAULT_TS_MAX_BATCH_DELAY))
        self._min_workers = int(os.environ.get(ts_parameters.MODEL_SERVER_MIN_WORKERS, DEFAULT_TS_MIN_WORKERS))
        self._max_workers = int(os.environ.get(ts_parameters.MODEL_SERVER_MAX_WORKERS, DEFAULT_TS_MAX_WORKERS))
        self._response_timeout = int(os.environ.get(ts_parameters.MODEL_SERVER_RESPONSE_TIMEOUT,
                                                    DEFAULT_TS_RESPONSE_TIMEOUT))
```
This means that at a model level it's not possible to change the startup parameter by just using their code imo
There's also a small typo that cause the torchserve config file  to be malformed, it's here (in torchserve.py)

```
    for key in user_defined_configuration:
        value = user_defined_configuration.get(key)
        if value:
            custom_configuration += "{}={}\n".format(key, value)

    if ENABLE_MULTI_MODEL:
        default_configuration = utils.read_file(MME_TS_CONFIG_FILE)
    else:
        default_configuration = utils.read_file(DEFAULT_TS_CONFIG_FILE)

    return default_configuration + custom_configuration

```
When they do `default_configuration + custom_configuration`  because there's no newline at the end of the default configuration file the last line is just glued with the first line of the custom configuration (which is created using the environment variables when deploying the model), actually if you run it in local mode and go in the container created and do a `cat /etc/sagemaker-ts.properties` you will see it.

Anyway, in order to get the startup timeout working I modified the code, then I created a new image from the base pytorch image where the modified code is used instead of the classic one, I didn't find any other ways to do it, the base image I used is `763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:2.4.0-gpu-py311-cu124-ubuntu22.04-sagemaker
`
The way its working is that I have changed this part of the code (in torchserve.py) 
```
    if ts_env.is_env_set() and not ENABLE_MULTI_MODEL:
        models_string = f'''{{\\
        "{DEFAULT_TS_MODEL_NAME}": {{\\
            "1.0": {{\\
                "defaultVersion": true,\\
                "marName": "{DEFAULT_TS_MODEL_NAME}.mar",\\
                "minWorkers": {ts_env._min_workers},\\
                "maxWorkers": {ts_env._max_workers},\\
                "batchSize": {ts_env._batch_size},\\
                "maxBatchDelay": {ts_env._max_batch_delay},\\
                "responseTimeout": {ts_env._response_timeout}\\
                }}\\
            }}\\
        }}'''
```
I added the  startup timeout  parameter in that file (and also in the  ts_parameters.py)

```
    if ts_env.is_env_set() and not ENABLE_MULTI_MODEL:
        models_string = f'''{{\\
        "{DEFAULT_TS_MODEL_NAME}": {{\\
            "1.0": {{\\
                "defaultVersion": true,\\
                "marName": "{DEFAULT_TS_MODEL_NAME}.mar",\\
                "minWorkers": {ts_env._min_workers},\\
                "maxWorkers": {ts_env._max_workers},\\
                "batchSize": {ts_env._batch_size},\\
                "maxBatchDelay": {ts_env._max_batch_delay},\\
                "responseTimeout": {ts_env._response_timeout},\\
                "startupTimeout": {ts_env._startup_timeout}\\
                }}\\
            }}\\
        }}'''
```
And that's the code I import in the new image

I have create a repo with the code an an example that you can run
[https://github.com/jeromeCondere/sagemaker_pytorch_user_defined](https://github.com/jeromeCondere/sagemaker_pytorch_user_defined)

With that I have been able to load a llama v3 directly in a ml.g5.2xlarge instance for inference even though it took about 20mins to download all the shards and load the model

**Comment by jeromeCondere** [comment]
Also if there's another way that is more simple, i'll be more than happy to switch for it
