### ISSUE TITLE
sagemaker.model_metrics not available in sagemaker==2.7

### ISSUE THREAD

**Issue by jonrossclaytor** [aws/sagemaker-python-sdk#2787]
**Describe the bug**
After upgrading to sagemaker sdk version 2.7, sagemaker.model_metrics is no longer available

**To reproduce**
1) Upgrade to sagemaker sdk version 2.7
2) Attempt ```from sagemaker import model_metrics```

**Expected behavior**
Module expected to be available

**Screenshots or logs**
Screen shot attached
![model_metrics](https://user-images.githubusercontent.com/25289340/144913104-70acd917-67fc-49a1-ab07-3f459fc05331.png)

**Comment by jonrossclaytor** [comment]
Other expected modules seem to be missing as well, for example: 

![pipeline](https://user-images.githubusercontent.com/25289340/144914031-abbadea5-dee5-4a29-aa9a-08f9db7dacdc.png)

**Comment by knikure** [comment]
Seems like this issue is resolved in newer versions of sagemaker like `v2.192.0`. I recommend upgrading the version of sagemaker to get rid of this error. 
<img width="902" alt="Screenshot 2023-12-13 at 7 14 34 AM" src="https://github.com/aws/sagemaker-python-sdk/assets/110067132/285c1d59-bea0-4df0-9de7-53fbd19808ab">
