### ISSUE TITLE
Inference request predictor.predict({'input':tensor_proto}) fails with 'TypeError: dtype: DT_FLOAT tensor_shape....is not JSON serializable'

### ISSUE THREAD

**Issue by VassAngels** [aws/sagemaker-python-sdk#299]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**:
Keras/LSTM
- **Framework Version**:
1.6
- **Python Version**:
2.7
- **CPU or GPU**:
CPU
- **Python SDK Version**:
?
- **Are you using a custom image**:
Yes

### Describe the problem
Hello, I have a custom Keras model trained in Sagemaker that goes through training without failing, and have also built an endpoint around it, however when I am trying to send an inference request using 
predictor.predict({'input':tensor_proto}) it fails with 'TypeError: dtype: DT_FLOAT tensor_shape....is not JSON serializable'. 

Any ideas as to where does the problem may lie? Something with tensorflow serving trying to serialise the request before it hits the endpoint? That would be quite useful to know as I assume that if it's happening before it hits the endpoint then I could probably cancel out that there is something wrong with the saved model at least at this stage?! 

My serving_input_function is: 
def serving_input_fn(params):
    tensor = tf.placeholder(tf.float32, shape=[1, 500])
    return tf.estimator.export.build_raw_serving_input_receiver_fn({INPUT_TENSOR_NAME: tensor})()

### Minimal repro / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

- **Exact command to reproduce**:

**Comment by yangaws** [comment]
Hi @VassAngels ,

We have an example notebook for using keras_model_fn

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_abalone_age_predictor_using_keras/tensorflow_abalone_age_predictor_using_keras.ipynb

From this notebook, what I see is, the prediction is called using predictor.predict(tensor_proto) instead of predictor.predict({'input':tensor_proto}). I tried to modify it to predictor.predict({'input':tensor_proto}) and got same error. So could you try using predictor.predict(tensor_proto) instead? Is there any reason that you have to wrap the tensor_proto in a json with 'input' as a key?

Thanks

**Comment by yangaws** [comment]
@VassAngels 

Cool. Glad you solved it!
