### ISSUE TITLE
Feature request: an option to delete /tmp/ folder when delete_endpoint?

### ISSUE THREAD

**Issue by yifeim** [aws/sagemaker-python-sdk#301]
Hi,

In local mode, the model artifacts are stored in /tmp/* folder and seems to require manual deletions. They accumulate to large volumes if the model is moderately large. I was wondering if we could specify a cleanup option at the end of delete_endpoint, as people mostly use local mode for testing purposes anyways.

https://github.com/aws/sagemaker-python-sdk/blob/704cd3169584f76e448239523cbb7b43429928f3/src/sagemaker/local/local_session.py#L141

Thanks.

**Comment by iquintero** [comment]
Hi @yifeim 

So the problem we have here is mostly impacting Linux. On OSX there is no need to manually delete the model artifacts. 

The problem on linux is the following:
the processes inside the container run as root. Any files they create (in this case the model) get created as root.  Since the python sdk is probably not running as root, we can't delete the files the container leaves behind. You could run the python sdk as root and then the cleanup would work.

We are looking for a solution for this, but we don't have an elegant solution yet.

Alternatively, you can specify where you want these files to be created by setting some path in **~/.sagemaker/config.yaml**

$ cat ~/.sagemaker/config.yaml
```
local:
    container_root: /Users/me/container_root
```

Hope this helps! We were aware of this issue which is why we set a log message to let our users know that there were some files left behind.

**Comment by andremoeller** [comment]
Hi @yifeim ,

I hope that answers your question -- feel free to reopen this issue if not. Thanks!

**Comment by yifeim** [comment]
Thanks. This might be a better solution - since the tmp space may not be big enough anyways.

**Comment by austinmw** [comment]
Hi @iquintero , my SM notebook instance does not have a `~/.sagemaker/config.yaml`. Am I looking in the wrong place?

**Comment by mathephysicist** [comment]
> Alternatively, you can specify where you want these files to be created by setting some path in **~/.sagemaker/config.yaml**

Is there a place we can view all the options for the config.yaml

**Comment by mathephysicist** [comment]
> Hi @iquintero , my SM notebook instance does not have a `~/.sagemaker/config.yaml`. Am I looking in the wrong place?

You will have to make it. make the directory then the file. Once you do it will load.
