### ISSUE TITLE
How to set the num_gpus?

### ISSUE THREAD

**Issue by willbadr** [aws/sagemaker-python-sdk#34]
I am not sure how to set the num_gpus? It's not mentioned anywhere in the docs.

**Comment by andremoeller** [comment]
Hi @willbadr ,

Thanks for using Amazon SageMaker!

I take it you mean for running MXNet training scripts, right? You don't have to set this since the SageMaker MXNet Container gets this value from the container's environment and injects it into your MXNet script's `train()` function for you.

Please let us know if this doesn't solve your question. Thanks!

**Comment by willbadr** [comment]
Thanks a lot for the answer. Yes, that's what I meant. Is there a way to
set it manually and pass it to the train() function?

**Comment by andremoeller** [comment]
Hi @willbadr,

You could use the `hyperparameters` dictionary in your MXNet script's `train()` function. Since this is just a `dict[string,string]`, you can choose whatever key you'd like and parse the number of GPUs from that entry's value. You can pass in this dictionary to the MXNet predictor's constructor:

https://github.com/aws/sagemaker-python-sdk/blob/157d8670977243f7f77327175d40364c885482b3/src/sagemaker/mxnet/estimator.py#L25
