### ISSUE TITLE
The Sagemaker pipeline step ModelStep() adds some additional strings to the name argument

### ISSUE THREAD

**Issue by vololab** [aws/sagemaker-python-sdk#3417]
The Sagemaker pipeline step ModelStep() possesses not typical properties within the argument "name", and namely: If the function ModelStep(name="registering-model") is applied, the name of this step is shown as "registering-model-RegisterModel". This is not observed in all other kinds of steps. Is it possible to eliminate the addition of "-RegisterModel" to the customer defined name?

**Comment by qidewenwhen** [comment]
Hi @vololab, thanks for using AWS SageMaker!

Regarding to the
>If the function ModelStep(name="registering-model") is applied, the name of this step is shown as "registering-model-RegisterModel"

it's working by design. 

The reason is, ModelStep is not a single step, instead, it's a collection of steps (i.e. [StepCollection](https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html#sagemaker.workflow.step_collections.StepCollection)), which may include multiple steps, like `_RepackModelStep`, `_RegisterModelStep` or `CreateModelStep`. Please find more information in https://sagemaker.readthedocs.io/en/stable/amazon_sagemaker_model_building_pipeline.html#model-step (especially the 2 last paragraphs in this section).

Therefore, the `-RegisterModel` is appended to clarify the different steps within the ModelStep collection. You'll also find `"-CreateModel"` to specify the `CreateModelStep` sub step and `"-RepackModel"` to specify the `_RepackModelStep` sub step.

Feel free to comment if you have further questions.

**Comment by qidewenwhen** [comment]
No response in the past 7 days so closing this issue. Feel free to reopen if you have further questions.
