### ISSUE TITLE
_RepackModelStep doesn't inherit Environment Variables

### ISSUE THREAD

**Issue by jmgray24** [aws/sagemaker-python-sdk#3545]
We have a proxy configured for HTTP/HTTPS. When the model repack step runs, it doesn't inherit the environment variables from the model, causing the ModelRepack to fail. This should pass through environment variables defined from the Model.

https://github.com/aws/sagemaker-python-sdk/blob/ea0d053266c20ceadd1e047c0ad01e40121583ca/src/sagemaker/workflow/model_step.py#L254

**Comment by jmgray24** [comment]
The pip install step was removed in #3143, so we should be unblocked by incrementing our version in our CI/CD pipelines, but repack should inherit any environment variables in order to appropriately respect customers configuration (i.e. proxy),

**Comment by qidewenwhen** [comment]
Hi @jmgray24, thanks for reaching out!

The repack step is an additional helper step for a CreateModel/ RegisterModel step. The repack step is only used for simply repacking custom dependencies and inference script into an existing model TAR archive, so that the new repacked model can be used in the subsequent CreateModel/ RegisterModel step. In other words, the environment variables do not take any effect in a repack step AFAIK. And as you already pointed out, it was the pip install issue in https://github.com/aws/sagemaker-python-sdk/issues/3143 that caused your repack step to fail, rather than the env vars, as upgrading the sagemaker sdk version unblocked you.

On the other hand, customer environment variables are passed to the CreateModel/ RegisterModel step directly so you'll see the env variables in the Model/ModelPackage console. I did a quick test and can verify that customer env vars were correctly displayed there.

Please let me know if this answer helps you. Thanks!
