### ISSUE TITLE
I have lost all my jobs / runs / trials since last week

### ISSUE THREAD

**Issue by arminvburren** [aws/sagemaker-python-sdk#3561]
Hello,

I am not sure if this related to a recent update but as of last week there was an update in the UI and now I can't find the tab with "Experiments / trial names / jobs". There's only an "Experiment" tab and it says "no Jobs" even though there was a lot of jobs before.

Also when i try to read the doc there is nothing that looks like what I was using before. Here are images of the script I was using to launch my jobs.

Can anyone explain what is happening ?

![1](https://user-images.githubusercontent.com/104854255/209794082-15c6defe-d8c9-4d3a-83c2-0923c69b7442.png)

![2](https://user-images.githubusercontent.com/104854255/209794712-933598c9-5a4c-49d2-87b9-51ee0ae71ecd.png)

![3](https://user-images.githubusercontent.com/104854255/209794087-dac9d23e-5cf4-41d7-853a-1ce57acce93e.png)

![4](https://user-images.githubusercontent.com/104854255/209794348-26ee7ab0-fb98-4924-8a72-75297deb9272.png)

**Comment by qidewenwhen** [comment]
Hi @arminvburren, thanks for reaching out!

Could you please check the "Unassigned Run" tab under "Experiments" view and see if your job data are there?
<img width="660" alt="image" src="https://user-images.githubusercontent.com/32910701/210857255-24d444f9-944e-4fe0-8654-26582d9934b6.png">

And FYI we recently updated the SageMaker Experiment SDK, which is now part of the [SageMaker SDK](https://sagemaker.readthedocs.io/en/stable/experiments/sagemaker.experiments.html#), and the UI in order to simplify the data scientist work. 
Please find more information in:
- Blog: https://aws.amazon.com/blogs/machine-learning/next-generation-amazon-sagemaker-experiments-organize-track-and-compare-your-machine-learning-trainings-at-scale/
- Developer Guide: https://docs.aws.amazon.com/sagemaker/latest/dg/experiments-create.html

**Comment by jkasiraj** [comment]
Hi @arminvburren, one of the changes that was made with the new UI was to hide auto created jobs in the Experiments view by default. If you click the settings icon that currently says 5/6 and update it to select all fields, you should be able to see your jobs. 

Do you see your data after doing so? I will also bring up this feedback to the team, as there has been discussion over whether or not to show them by default

**Comment by arminvburren** [comment]
Yes I see them now. Can you explain to me in like a sentence what's exactly the difference between a Run and a job ? Also, what has become of trials ? 

If jobs are 'current training processes' and Run are 'finished processes' i do think you should absolutely show them since I was also confused by that (I was launching trainings and they were not appearing nowhere)

**Comment by arminvburren** [comment]
By the way I'd also like to be able to check if a job is running and stop it, but i can't see exactly where this is

**Comment by jkasiraj** [comment]
```
Yes I see them now thanks. 
```
Glad it's working now!

```
Can you explain to me in like a sentence what's exactly the difference between a Run and a job ?
```
The sentence version: 
* A job maps to a Trial Component and a Trial Component is a Run.

The slightly longer version:
* SageMaker jobs are run on containers for training, processing, tuning, transforming
* Trial Components are what existed in the old UI and continue to be carried forward in the new UI
* Job Trial Components are automatically created when a job is created in order to keep track of useful data
* Runs are Trial Components and so a Job Trial Component is a type of Run

```
Also, what has become of trials ?
```
Trials are now `Run Groups`, which is a column in the Runs table

```
If jobs are 'current training processes' and Run are 'finished processes' 
```
This is incorrect, a run can be finished or in progress and a job can too

```
i do think you should absolutely show them since I was also confused by that (I was launching trainings and they were not appearing nowhere
```
Will pass it on!

```
By the way I'd also like to be able to check if a job is running and stop it, but i can't see exactly where this is
```
Makes sense, we are definitely thinking about this as a future improvement. In the meantime you could use the SageMaker console if you have access to it in the AWS console

**Comment by jkasiraj** [comment]
Marking this issue as closed, an update to allow jobs to be visible by default will be coming out in the near future
