### ISSUE TITLE
Training job conflict error when installing local src

### ISSUE THREAD

**Issue by cirofdo** [aws/sagemaker-python-sdk#3721]
I'm setting up a simple pipeline with preprocessing, training and inference.
But when it gets on the training job I get an error when trying to install local src lib withing the requirements.txt. This is the error:
`ERROR: Cannot install src 0.0.0 (from /opt/ml/code) because these package versions have conflicting dependencies.`

```
    ├── pipeline.py    <- file that initiates the pipeline
    ├── requirements.txt 
    │
    └── src 
        │
        ├── data
        │   └── make_dataset.py
        │
        └─ models
            ├── predict_model.py
            └── train_model.py
```

On the pipeline.py I first run the `make_dataset.py` and it runs without error.
Then on the training job I pass  `entry_point="src/models/train_model.py"` and `source_dir="."`. Then it runs pip install with the requirements.txt (that contains a `-e .` to install `src`)

The full error:
![image](https://user-images.githubusercontent.com/15761737/225328553-f7b3cba6-bbe2-4f1b-9903-5b45e1546f87.png)

Weird because why it gives conflict error even when there is no other src installed.

**Comment by martinRenou** [comment]
Were you able to find the fix for your issue?

As far as I can tell, it seems weird to specify `-e .` in your `requirements.txt` file, as your local directory is not a valid installable Python project. 

I understand that your `requirements.txt` should only contain your Python dependencies and you should probably remove the `-e .` entry from there.

**Comment by martinRenou** [comment]
Closing as answered, feel free to continue the discussion if needed
