### ISSUE TITLE
R: TypeError: function() missing 1 required positional argument: 'self' 

### ISSUE THREAD

**Issue by SonicV2** [aws/sagemaker-python-sdk#377]
Hi, Will be great if I can have some help on this issue

### System Information
- **Python Version**: 3.6
- **CPU or GPU**: M5.large
- **Python SDK Version**: 3.6
- **Are you using a custom image**: Amazon Linux Deep Learning AMI

### Describe the problem

Ran into a problem when calling functions from R studio. Installed reticulate on R which allows me to use python in R. 

sagemaker <- import ("sagemaker")
session <- sagemaker$Session
bucket <- session$default_bucket()
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: default_bucket() missing 1 required positional argument: 'self'

### Minimal repro / logs

Was attempting to follow this tutorial: https://aws.amazon.com/blogs/machine-learning/using-r-with-amazon-sagemaker/

- **Exact command to reproduce**:

**Comment by nadiaya** [comment]
`default_bucket` expects `self` as the first argument: 
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/session.py#L162

Unfortunately I am not very familiar with `reticulate` package to advice on how exactly passing `self` works, but it seems like the error might be because you need to instantiate a `Session` instance first by calling `session <- sagemaker$Session()`. Which is also the difference between your code and tutorial:
```r
library(reticulate)
sagemaker <- import('sagemaker')
session <- sagemaker$Session()
bucket <- session$default_bucket()
```

Hopefully this helps.
