### ISSUE TITLE
Setting `code_location` of an Estimator to a ParameterString results in an Exception

### ISSUE THREAD

**Issue by david-waterworth** [aws/sagemaker-python-sdk#4204]
**Describe the bug**

This seems similar to https://github.com/aws/sagemaker-python-sdk/issues/3195

When I set `code_location` of an `Estimator` to a `ParameterString` the exception `AttributeError: 'ParameterString' object has no attribute 'decode'` is thrown by `training_pipeline.upsert`. 

I can set `output_path` no problem, (I'd also add that I always have to set these to the same s3_prefix or I end up with code and model artifacts in different buckets - ideally setting output path would also set code_location to the same unless code_location was specifically passed differently.

**To reproduce**
```
import yaml
from sagemaker.huggingface import HuggingFace

output_path = ParameterString(
    name="OutputPath",
    default_value=f's3://{S3_BUCKET}/{S3_PREFIX}'
)

estimator = sagemaker.huggingface.HuggingFace(
        entry_point="train.py",  # fine-tuning script to use in training job
        source_dir="scripts",  # directory where fine-tuning script is stored
        instance_type="ml.g4dn.xlarge",  # instance type
        instance_count=1,  # number of instances
        role=role,  # IAM role used in training job to acccess AWS resources (S3)
        transformers_version="4.28",  # Transformers version
        pytorch_version="2.0",  # PyTorch version
        py_version="py310",  # Python version
        
        output_path=output_path,    # This is ok
        code_location=output_path, # This produces an exception
    
        disable_profiler=True,
        sagemaker_session=session,
    )

# Configure Pipeline Step - 'TrainingStep'
train_model_step = TrainingStep(
    name='TrainModel',
    estimator=estimator,
    cache_config=cache_config,
)

pipeline_name = 'train-baseline-pipeline-1'
step_list = [
             train_model_step
]

training_pipeline = Pipeline(
    name=pipeline_name,
    parameters=[output_path],
    steps=step_list
)

training_pipeline.upsert(role_arn=role)
```

**Comment by qidewenwhen** [comment]
Hi @david-waterworth thanks for reaching out!

To clarify, the `code_location` does not support any PipelineVariable, e.g. Parameter. This is indicated in the doc string of its base class (see below). Ref: https://sagemaker.readthedocs.io/en/stable/api/training/estimators.html#sagemaker.estimator.Framework

> container_log_level ([int](https://docs.python.org/3/library/functions.html#int) or [PipelineVariable](https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html#sagemaker.workflow.entities.PipelineVariable)) – The log level to use within the container (default: logging.INFO). Valid values are defined in the Python logging module.
code_location ([str](https://docs.python.org/3/library/stdtypes.html#str)) – The S3 prefix URI where custom code is uploaded (default: None). You must not include a trailing slash because a string prepended with a “/” is appended to code_location. The code file uploaded to S3 is ‘code_location/job-name/source/sourcedir.tar.gz’. If not specified, the default code location is ‘s3://output_bucket/job-name/’.

The parameterizable variables would have a `PipelineVariable` type hint while the `code_location` does not.

--------
The reason why code_location does not support vs `output_path` does is, the `code_location` is used in pipeline build/compile time to upload any user input local files so it should not be a variable parsed only in the execution runtime.
On the other hand, `output_path` is used only in execution time to upload the step output, so it does support pipeline variables.

**Comment by david-waterworth** [comment]
Thanks @qidewenwhen that makes sense, I understand the constraint. But I'm having issues implementing an SKLearn pipeline. The docstring above says `code_location/job-name/source/sourcedir.tar.gz` but that's not what happens if you use an Estimator in a pipeline, it's actually uploaded to

`code_location/TrainModel-8305349b316331ec49c0d2c212e70d45/source/sourcedir.tar.gz` when the jobname is `pipelines-bxnbiy97sh7t-TrainModel-A877tO8u9E` 

The problem is I need to access the source in a subsequent step but cannot because I cannot find at runtime where it's putting the code. i.e.

## Training Step
```
from sagemaker.sklearn.estimator import SKLearn
from sagemaker.workflow.steps import TrainingStep
from sagemaker.inputs import TrainingInput

code_location = f"s3://{default_bucket}"

estimator = SKLearn(
    entry_point="steps/train/train.py",
    code_location=code_location,
    framework_version=FRAMEWORK_VERSION,
    instance_type="ml.c4.xlarge",
    role=role,
    sagemaker_session=sagemaker_session,
    hyperparameters={"max-iter": 1000, "early-stopping": True},
)

train_model_step = TrainingStep(
    name='TrainModel',
    estimator=estimator,
    cache_config=cache_config,
    inputs={ # SM_CHANNEL_TRAIN
        "train": TrainingInput(s3_data=preprocessor_step.properties.ProcessingOutputConfig.Outputs["train"].S3Output.S3Uri),  
    },
)
```

## Register Step
```
from sagemaker.model import Model
from  sagemaker.sklearn.model import SKLearnModel
from sagemaker.workflow.model_step import ModelStep
from sagemaker.workflow.functions import Join

# Get uri of sagemaker sklearn inference container
image_uri = sagemaker.image_uris.retrieve(
    framework="sklearn",
    region=region,
    version=FRAMEWORK_VERSION,
    image_scope="inference",
    py_version="py3",
    instance_type="ml.m5.xlarge",
)

# Construct model
model = Model(
    image_uri=image_uri,
    model_data=train_model_step.properties.ModelArtifacts.S3ModelArtifacts,
    env={
         "SAGEMAKER_PROGRAM": train_model_step.properties.HyperParameters["sagemaker_program"], #the entry point present in sourcedir.tar.gz
         "SAGEMAKER_SUBMIT_DIRECTORY": train_model_step.properties.HyperParameters["sagemaker_submit_directory"]
    },
    sagemaker_session=pipeline_session,
    role=role,
)

# Generate registration args for model
register_args = model.register(
    model_package_group_name=model_package_group_name,
    content_types=["text/csv", "application/json", "application/x-npy"],
    response_types=["text/csv", "application/json", "application/x-npy"],
    approval_status="Approved",
)

# create register model step
register_model_step = ModelStep(
    name="PipelineModel",
    step_args=register_args,
)
```

I've tried multiple attempts to get this to work but I cannot get set SAGEMAKER_SUBMIT_DIRECTORY to the s3 location where the training code was uploaded to (it also contains `model_fn`. 

When I run the pipeline, `train_model_step.properties.HyperParameters["sagemaker_submit_directory"]` seems to contain the correct value after execution has completed but it seems that I'm using it before it's set.

I cannot find any other way of finding out where the code will be uploaded to?

The only other option appears to be creating separate scripts (train.py and inference.py) and generating the s3 location for inference.py myself?

What would you recommend?

**Comment by qidewenwhen** [comment]
Hi @david-waterworth sorry for the super late response. In case you are still blocked by the issue, here are my suggestions:

> When I run the pipeline, train_model_step.properties.HyperParameters["sagemaker_submit_directory"] seems to contain the correct value after execution has completed but it seems that I'm using it before it's set.

This should be fine because the properties reference of `train_model_step` would build dependency relationship between these two steps, so it looks like: `train_model_step` -> `register_model_step`
Once the `train_model_step` is completed, the "sagemaker_submit_directory" would be ready to consume by the following steps.

However, my only concern for this approach is, HyperParameters["sagemaker_submit_directory"] may add an extra quote `"..."` around the string value, so there should be some logics in `inference.py` to handle that.

If this approach with `train_model_step.properties.HyperParameters["sagemaker_submit_directory"]`, as you mentioned, `creating separate scripts (train.py and inference.py) ` would be a good choice. And based on my observation, this seems to be a good practice to separate these files as they may grow independently.

Apologize again for the delay.

**Comment by qidewenwhen** [comment]
Closing the issue as we did not hear back in past 3 weeks. Feel free to reopen if you have further questions. Thanks!
