### ISSUE TITLE
Using Tensorflow with docker image from docker hub

### ISSUE THREAD

**Issue by vbvg2008** [aws/sagemaker-python-sdk#437]
Please fill out the form below.

### Describe the problem
from the description of sagemaker.tensorflow.TensorFlow, it says we can pass an "image_name" argument which can be either ECR url or docker hub image. 

I tried using a docker hub image but haven't succeeded.   for example, I want to use tensorflow/tensorflow:1.11.0-gpu on docker hub.  what I tried was:

```
from sagemaker.tensorflow import TensorFlow

...

estimator = TensorFlow(
    .....
    image_name = "tensorflow/tensorflow:1.11.0-gpu"
)
```

I got the following error:

<An error occurred (ValidationException) when calling the CreateTrainingJob operation: Invalid training image. Please provide a valid Amazon Elastic Container Registry path of the Docker image that contains the training algorithm.>

Any ideas on how to use docker hub images for tensorflow estimator training?

**Comment by iquintero** [comment]
Hi @vbvg2008 

Sorry for the confusion. At the moment SageMaker does not support docker hub. We will fix our docs. Also please note that even if you pulled that image yourself and pushed it to ECR it won't work. The reason is that our Tensorflow images have our support libraries and that is what the Tensorflow Estimator expects. image_name is meant to support customers who need to customize our images with their own extra packages, custom binaries etc.

You can find our Tensorflow image at:
https://github.com/aws/sagemaker-tensorflow-container

If you notice the last commit already added support for 1.11 and we will support it soon, however you can build the image yourself and push it to ECR and use it right now before we officially release it.

Hope this helps.

**Comment by vbvg2008** [comment]
@iquintero Hi, thanks for your reply. Tensorflow 1.11.0 is all I need, I'm glad to find out the tensorflow 1.11.0 container is available already.   

So before the container is officially released on sagemaker, can I use image here https://github.com/aws/sagemaker-tensorflow-container/blob/master/docker/1.11.0/final/py2/Dockerfile.gpu and push it to ECR and use it in sageamaker? 

Also I noticed that in the docker file, there is a  pip install  "sagemaker-tensorflow>=1.10,<1.11" , is it true that sagemaker-tensorflow 1.10 can also support tensorflow 1.11?

**Comment by iquintero** [comment]
Yeah if you build the image and push it to ECR it should work

pass it as a parameter `image_name=<your ecr url>`

As for the version yeah 1.10 can also support 1.11

**Comment by vbvg2008** [comment]
@iquintero Thanks for clarification.   I was trying to build the image in my sagemaker notebook instance and ran into a missing file error. 

from the docker image mentioned earlier, there are two lines:
```
ARG framework_support_installable=sagemaker_tensorflow_container-1.0.0.tar.gz
...
COPY $framework_support_installable .
```
I believe I don't have the "sagemaker_tensorflow_container-1.0.0.tar.gz" and it gave me an error while executing the line COPY $framework_support_installable .

<COPY failed: stat /var/lib/docker/tmp/docker-builder426220576/sagemaker_tensorflow_container-1.0.0.tar.gz: no such file or directory>

any ideas on how to get that file?

**Comment by vbvg2008** [comment]
@iquintero  thank you so much for your help! it worked.

FYI, i had to remove the following line of the docker file to make it work.  
```
rm $framework_installable && \
```
Otherwise, the variable is empty and will cause error during rm

**Comment by iquintero** [comment]
Glad it worked for you! 
Feel free to re-open if you have any follow up questions.
