### ISSUE TITLE
input data config ignored in local mode?

### ISSUE THREAD

**Issue by yifeim** [aws/sagemaker-python-sdk#451]
The local image clearly ignores context_type of an input,

https://github.com/aws/sagemaker-python-sdk/blob/385d40ab2325812104c050bdfe600764801ca550/src/sagemaker/local/image.py#L246

despite they somehow passed unit test

https://github.com/aws/sagemaker-python-sdk/blob/c8006fab13f8fb2a9368f93e676c029c5a8862ae/tests/unit/test_local_session.py#L328

My same custom model runs in remote but not in local. This inspires my question: how are context types detected? E.g., by file suffix?

Thanks.

**Comment by nadiaya** [comment]
Thank you for reporting it. This does look like a bug.

**Comment by iquintero** [comment]
Hi @yifeim  this is fixed in #449 

Local Mode will now work the same way as SageMaker does. Basically if you provide a content_type it will be passed to inputdataconfig.json. If you don't then there will be no ContentType key in the json file. It is up to your algorithm to define a default if it needs to.  This change makes it consistent with SageMaker.

**Comment by yifeim** [comment]
Thanks a lot for the fast response! Will take a look.

**Comment by nadiaya** [comment]
Fixed has been merged. Resolving.

**Comment by yifeim** [comment]
Good job! The other changes are also interesting. Thanks a lot!
