### ISSUE TITLE
ModelStep name includes "-RegisterModel" suffix

### ISSUE THREAD

**Issue by david-waterworth** [aws/sagemaker-python-sdk#4765]
**Describe the bug**

**To reproduce**

```
model_step = ModelStep(name="Model", step_args=model_args)
```

```
steps = execution.list_steps()
steps
```

```
[{'StepName': 'Model-RegisterModel',
  'StartTime': datetime.datetime(2024, 7, 2, 15, 32, 10, 60000, tzinfo=tzlocal()),
  'EndTime': datetime.datetime(2024, 7, 2, 15, 32, 11, 390000, tzinfo=tzlocal()),
  'StepStatus': 'Succeeded',
  ,,,
```

The actual model step name is "Model-RegisterModel"

**Expected behavior**
Ability to set the step name for ModelStep like all other *Step's

In particular it's confusing when I use `SelectiveExecutionConfig` because I need to anticipate the suffix sagemaker adds to my step name.

**Screenshots or logs**
![image](https://github.com/aws/sagemaker-python-sdk/assets/5028974/87a09055-6e8f-4b64-96d5-d08757cb0fa1)

**Comment by qidewenwhen** [comment]
Hi @david-waterworth , thanks for reaching out!

It is expected for ModelStep name to include a "-RegisterModel" suffix, because ModelStep is not a Step type (e.g. TrainingStep), rather it's a StepCollection [see here](https://github.com/aws/sagemaker-python-sdk/blob/1b4dc7cfc4ca5b3fa3c9cfefe5a57d35449000fc/src/sagemaker/workflow/model_step.py#L37).

As a StepCollection, the ModelStep is actually a list of steps. Though in your case, the model step collection has one register model step only, in some cases it can include a repack model step (used to repack the model artifacts as per requirements from different model server), and a register/create model step. 

Thus, we use the naming template of `<user input ModelStep name>-<RegisterModel/CreateModel/RepackModel>` to differentiate the sub steps.

As for configuring the SelectiveExecutionConfig, you can retrieve the step list of ModelStep via `model_step.steps` and get the name of each sub step from there. In this way, you may not need to hard code the suffix in your code.

**Comment by qidewenwhen** [comment]
Closing the issue as we did not hear back in past three months. Feel free to reopen if you have further questions. Thanks!
