### ISSUE TITLE
Unexpected behaviour using a manifest file (or just the relative path of data)

### ISSUE THREAD

**Issue by audriusuzkuraitis** [aws/sagemaker-python-sdk#723]

**Comment by audriusuzkuraitis** [comment]
### System Information

* **Framework:** xgboost
* **Framework Version:** 0.82
* **Python Version:** 3.7.1
* **CPU or GPU:** cpu:
* **Python SDK Version:** sagemaker version 1.18.2
* **Are you using a custom image:** no

### Describe the problem

Hello,

I have an s3 directory of daily data with folders corresponding to the specific day.
I'm working with python and need to train some models with said data in a moving time window manner using XGBoost, therefore I created manifest files necessary for the s3_input with respect to the file format provided in the Amazon's documentation (the "part-..." files are files written in libsvm format, which I provide as the content_type parameter), i.e.
[
{"prefix": "s3://customer_bucket/some/prefix/"},
"relative/path/2019-02-02/part-00001",
"relative/path/2019-02-03/part-00020",
"relative/path/2019-02-03/part-00025",
...
].
The manifest format *is* perfectly valid and upon start I get presented with the correct data size in the "File size need to be processed in the node:" clause. But then it loads data from only one of the subdirectories listed (yes, subdirectories - e.g. outputs "NxM matrix with X entries loaded from /opt/ml/input/data/train/ *some/prefix/relative/path/2019-02-03* ", so not even just one of the keys, but everything from one of the subdirectories containing some of the files). And the subdirectory appears to be chosen at random each time.

I tried to dig deeper into the functions, but it all seems to boil down to whatever happens at the API calls.

Could anybody help me with this?

*EDIT:*
It appears this is the same behaviour when trying to pass a single s3 relative path, containing other subdirectories - one of them is chosen at random and the data is loaded (e.g. respectable folder for one day inside of "s3://customer_bucket/some/prefix/relative/path/" in my specific case).

**Comment by laurenyu** [comment]
thanks for your patience! we've reached out to the team that owns XGBoost about your issue to see if they have some insight.

**Comment by yijiezz** [comment]
Hi,
Thanks for your patience!

SageMaker XGBoost currently required all the input data are under the same folder path, either "/opt/ml/input/data/train" or "/opt/ml/input/data/train/subfolder". 

If the input data are spread across multiple subfolders , SageMaker XGBoost was unable to iterate through the all the folders and collect the data. We'll treat this as a customer request and put it in the roadmap.

At the moment, you'll need to move all the data into a same folder for the training. Manifest file might not be applied to this case since it will keep all the subpaths as folder paths.

Sorry for the inconvenience.

**Comment by jewelltp** [comment]
@yijiezh has this been resolved yet?

**Comment by jewelltp** [comment]
@yijiezh sorry, was an error on my part. This looks to be fixed.
