### ISSUE TITLE
Unused variable LATEST_VERSION in TensorFlow estimator

### ISSUE THREAD

**Issue by mmeidl** [aws/sagemaker-python-sdk#754]
This issue was reported by AWS customer Nishank Singla from GE Healthcare.

This is a small correction for some default variables used in the TensorFlow Estimator class.

It looks like in the TF 1.12 upgrade, someone meant to replace `TF_VERSION` with `LATEST_VERSION`: https://github.com/aws/sagemaker-python-sdk/blob/2763f9ac16cae778905dddbaa69ea63f4ae39adc/src/sagemaker/tensorflow/estimator.py#L174

TF_VERSION is still set to 1.11: https://github.com/aws/sagemaker-python-sdk/blob/2763f9ac16cae778905dddbaa69ea63f4ae39adc/src/sagemaker/tensorflow/defaults.py#L15

And LATEST_VERSION is not actually used as the default in the constructor: https://github.com/aws/sagemaker-python-sdk/blob/2763f9ac16cae778905dddbaa69ea63f4ae39adc/src/sagemaker/tensorflow/estimator.py#L231-L233

**Comment by laurenyu** [comment]
@mmeidl thanks for the bug report! We've moved away from changing the default version with framework version upgrades because doing so can cause a breaking change: if the new framework version or our Docker images for that version have breaking changes, then simply upgrade this SDK's version could cause previously-working code to suddenly not work.

However, the warning that `framework_version` is not set should be updated with the correct "latest version" of TF. I've fixed that in #756.

**Comment by Nishanksingla** [comment]
What's the default TensorFlow version that will be used if I don't define the framework_version?

**Comment by mmeidl** [comment]
Thanks @laurenyu for the quick response and PR. 

It sounds to me like you plan to keep `TF_VERSION` as the "default"  version fixed at 1.11, while `LATEST_VERSION` is updated on each version release. I can see this is a pattern for other Frameworks implementations too.

Clearly this caused some confusion to readers, so maybe the best way forward would be to add brief comments where each variable is defined, describing how they are used and updated?

Or, would you consider renaming `TF_VERSION` to `TF_DEFAULT_VERSION`?

**Comment by laurenyu** [comment]
That's correct, the default version is going to be frozen at 1.11. Adding some documentation around this is definitely a good idea. Our guidance going forward is to use the `framework_version` argument to explicitly define which version of TF (or any other framework/toolkit) is desired when instantiating an estimator.

Renaming the variable would technically be introducing a breaking change since it's a public variable. We've been trying to avoid releasing breaking changes, but perhaps in the future we'll have a release that can help clean up the experience around this.

**Comment by Nishanksingla** [comment]
Ok. Thank you for the clarification.

**Comment by laurenyu** [comment]
the changes have now been released. closing this issue.
