### ISSUE TITLE
Object2Vec - Using tied weights gives different embedding results from in0 and in1 channels

### ISSUE THREAD

**Issue by tkocmathla** [aws/sagemaker-python-sdk#813]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Object2Vec
- **Python Version**: 3.7
- **CPU or GPU**: ml.p3.2xlarge instance
- **Python SDK Version**: 1.21.2
- **Are you using a custom image**: no

### Describe the problem
When using the hyperparameter tied_token_embedding_weight=True, I expected that calling the inference endpoint to retrieve embeddings would give the same result whether the in0 or in1 channel was used. In fact, the results are different, suggesting that two different embeddings were learned for the two channels.

Am I misunderstanding the relationship between tied_token_embedding_weight and the embeddings retrieved from inference?

### Minimal repro / logs
Set hyperparameter tied_token_embedding_weight=True, train object2vec model, and do inference for embeddings. Compare the results when passing input into in0 channel vs. in1 channel.

**Comment by ChoiByungWook** [comment]
Hello @tkocmathla,

Good question!

Let me route your question to experts of Object2Vec.

Until then, please let me know if there is anything I can answer or clarify.

Thanks!

**Comment by pnpnpn** [comment]
Hello @tkocmathla , 

The `tied_token_embedding_weight` hyperparameter ties the weight of the **token** embedding layer of the two encoders. Note that if you are using HCNN or BiLSTM, the inference embedding outputs of  in0 and in1 will still be different because the weights of HCNN and BiLSTM are not tied in that case. However, if you use `pooled_embedding` (averages the embeddings of all of the tokens in the input) for both arms, then the inference embedding outputs would be the same. 

Thanks for using Object2Vec.
