### ISSUE TITLE
Object2Vec - ClientError: Inconsistent vocab for in1 found

### ISSUE THREAD

**Issue by kianho** [aws/sagemaker-python-sdk#834]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Object2Vec
- **Framework Version**:
- **Python Version**: 3.6
- **CPU or GPU**:
- **Python SDK Version**: 1.24.0
- **Are you using a custom image**: No

### Minimal repro / logs

The sagemaker jupyter notebook that reproduces this error can be found here:
- https://gist.github.com/kianho/6b22bccafb9329274d925146d0fda029

### Describe the problem
When training an Object2Vec model with a (deliberately) small vocabulary, the training job fails because an input word/token from `in1` of the training data is not found to be within its pre-allocated vocabulary size.

For example
```
ValueError: Error for Training job object2vec-training-job-debug: Failed Reason: ClientError: Inconsistent vocab for in1 found. Vocab id "2" is not less than vocab_size=2
```
However, I had set `enc1_vocab_size=3` prior to calling `fit`
```python
...
epochs = 1

enc0_vocab_size = 2
enc1_vocab_size = 3

enc0_max_seq_len = 1
enc1_max_seq_len = 1

# set some basic hyperparameters
hparams = dict(
    epochs=1,
    enc0_vocab_size=enc0_vocab_size,
    enc1_vocab_size=enc1_vocab_size,
    enc0_max_seq_len=enc0_max_seq_len,
    enc1_max_seq_len=enc1_max_seq_len    
)

o2v.set_hyperparameters(**hparams)
...
o2v.fit(
    inputs={ "train": s3_input(train_s3_path, content_type="application/jsonlines") },
    job_name=TRAIN_JOB_NAME
)
```
It appears that the wrong `vocab_size` is used for `in1`.

The training data used to fit the model:
```
{ "label": 1, "in0": [0], "in1": [2] }
{ "label": 0, "in0": [1], "in1": [1] }
{ "label": 1, "in0": [0], "in1": [0] }
```

**Comment by chengtang48** [comment]
Hi

Since the user uses the default "enc1_network", which is set to "enc0", enc1's HP's are copied internally from those of enc0's. This means your enc1 is effectively setting its vocab_size to be 2 (matching that of enc0_vocab_size). 

To resolve this, set enc1_network to be an explicit network type (for example, "hcnn").

**Comment by pnpnpn** [comment]
Since the user uses the default "enc1_network", which is set to "enc0", enc1's HP's are copied internally from those of enc0's. This means your enc1 is effectively setting its vocab_size to be 2 (matching that of enc0_vocab_size). 

To resolve this, set enc1_network to be an explicit network type (for example, "hcnn").
