### ISSUE TITLE
Is requirements.txt used in MXNet serving image?

### ISSUE THREAD

**Issue by public-git-ui** [aws/sagemaker-python-sdk#957]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: MxNet
- **Framework Version**: 1.4
- **Python Version**: py3
- **CPU or GPU**: CPU
- **Python SDK Version**: 1.34.2
- **Are you using a custom image**: No

### Problem

I added requirement.txt to my script directory and it is picked up during training but not when the prediction endpoint was started. Is that expected?

API used:
```
from sagemaker.mxnet import MXNet

m = MXNet('estimator.py',
              role=role,
              train_instance_count=1,
              train_instance_type="ml.m4.xlarge",
              sagemaker_session=sagemaker_session,
              py_version='py3',
              framework_version='1.4',
              hyperparameters=hyperparameters)

m.fit({'training': training_set})

predictor = m.deploy(initial_instance_count=1, instance_type='ml.c4.xlarge', endpoint_name=None)

**Comment by knakad** [comment]
Thanks for reaching out!
This is on our roadmap, but is not currently supported.

Here are a couple workarounds instead:
* You should be able to create a model archive which contains the model artifacts and its dependencies by following this wiki: https://github.com/awslabs/mxnet-model-server/tree/master/model-archiver#creating-a-model-archive
* A simpler workaround is to simply `pip install` in the model_fn function per https://sagemaker.readthedocs.io/en/stable/using_mxnet.html#model-loading

**Comment by public-git-ui** [comment]
Thanks for the reply. 

`pip install` is not good option for us as we don't want to risk suffering downtime when pypi is not available. From our experience, our endpoints did go down for this reason and worse it did so silently, none of our alarms were raised for some reason.

Ideally when this feature is implemented, the pip execution will be done and cached when the endpoint is created/updated so it will be available when compute instances are added/rotated.

**Comment by humanzz** [comment]
@knakad to expand on @public-git-ui's comments.
We've been early users of SageMaker, and from that early on we realized the need to have more libraries in the containers and employed the `pip install` trick. We have a CD pipeline that deploys our SageMaker endpoints using CloudFormation. Our observation has been that there's occasional failures because of `pip install`-ing things. That tended to happen at deployment time.

An even worse thing we saw was when the SageMaker instance was being recycled/replaced. At this point, `pip install` failed silently and the endpoint ended up being in an inconsistent state where it was responding with 500 errors to all requests.

Due to the absence of SageMaker endpoint health metrics, it took as a while to realize this issue was happening which was really problematic.

`requirements.txt` is a great way to customize the containers for both traning and serving and we'd really like to use that. However, on the SageMaker-side of things I believe you need to distinguish between errors happening due `pip` issues and others issues to possibly deal with them differently and provide the proper feedback/metrics for SageMaker users.

**Comment by jesterhazy** [comment]
@humanzz these are great points. We'll keep them in mind as we implement the `requirements.txt` support for this container.

**Comment by laurenyu** [comment]
related: https://github.com/aws/sagemaker-inference-toolkit/issues/9

**Comment by akartsky** [comment]
The new images are released.
Code will be available in the pubic repos in a couple of days.
